### ISSUE TITLE
make a similar one for vscode

### ISSUE THREAD

**Issue by lakshits11** [nihaals/visual-studio-code-insiders-arch#1]
Hy!
Can you please make a similar repo for vscode (not insiders) too or can you please instruct on how to make a similar repo ? I am using arch and some packages are not updated in arch package manager at the same pace.

**Comment by nihaals** [comment]
Due to the (relative) [lower frequency](https://aur.archlinux.org/cgit/aur.git/log/?h=visual-studio-code-bin) of non-insiders VSCode, I would recommend using the main AUR package and flagging the package out of date when needed as is standard procedure. Keeping packages on the AUR as much as possible keeps the visibility higher and helps as many people as possible.

Most Linux package managers don't have tooling similar to e.g. Homebrew's `livecheck` and `bump` (which is why I had to implement it all manually) and so is often just more manual. The reason this wasn't followed for VSCode Insiders is due to the much higher rate of updates, making manual updates quite a tedious task. This is why [Homebrew's cask uses `:latest`](https://github.com/Homebrew/homebrew-cask-versions/blob/5d6a9873f0425075a78072aad3726349aedfc30d/Casks/visual-studio-code-insiders.rb#L4), as even with tooling to automate updating, merging those updates takes a lot of bandwidth.

In my opinion, this kind of repo should be made as a last resort, and it only adds nicer support for things like yay, just not bumping the version in `PKGBUILD` is also usable. VSCode also has version numbers in the URL which helps keep AUR updates stable. I would recommend instead building automation to make it easier and faster to flag packages you're interested in out of date on AUR instead of recreating this repo.
