### ISSUE TITLE
Retry the `build-gh-pages` workflow stage when previous attempt failed

### ISSUE THREAD

**Issue by julian-poidevin** [nihaals/visual-studio-code-insiders-arch#3]
Due to #2, the `build-gh-pages` workflow stage sometime fails (e.g. [22850](https://github.com/nihaals/visual-studio-code-insiders-arch/actions/runs/5109443290/jobs/9184315423))

In next scheduled workflow runs _(e.g. [22851](https://github.com/nihaals/visual-studio-code-insiders-arch/actions/runs/5109911510) and [22852](https://github.com/nihaals/visual-studio-code-insiders-arch/actions/runs/5110364369))_, **the `build-gh-pages` stage is skipped where it should run again due to the previous failure**.

![image](https://github.com/nihaals/visual-studio-code-insiders-arch/assets/8756421/30754af6-fa1f-448b-afb0-59064508eeca)

**Comment by nihaals** [comment]
This is an interesting problem and I'm not sure what the best solution would be. As this workflow only triggers the GitHub Pages deploy once for each new update, it's more of an issue than other workflows, as that update is just skipped, and so reducing the fails/handling fails in that deploy job would help keep the Pacman repo more up-to-date.

Fetching the status of the previous run isn't great and I wouldn't want to add anything like that unless GitHub Actions added syntax for that directly in the workflow instead of calling the API yourself. Adding an extra step to the job that's just a copy-paste of the previous step feels like too much of a workaround and makes the workflow messier. I think my favourite approach would be adding something like a `LATEST_VERSION` file to the `gh-pages` branch and then comparing that file instead of using an `if` for the whole job. This would also avoid race conditions from having another workflow that periodically makes sure the main branch and the Pacman repo are in sync.

Another thing to keep in mind is the added complexity. The current solution is the more "correct" one and manages to completely avoid the deploy job as the two branches are always expected to be in sync and any issue is likely an infrastructure issue/outage (in this case random GitHub hiccups). If this was something updated much more occasionally, for example an app with ~monthly releases, the deploy job succeeding would be much more important, but with how often there are new Insiders updates, the impact of a single fail is fairly minimal. In the case of less regular deploys, I think I would prefer to manually retry the job.

This workflow isn't updated very often and fortunately "just works" as I tried to make it stable, so the added complexity of adding a check like this doesn't have much of an impact on code maintainability, but does have an impact on the workflow's efficiency (even if GitHub Actions usage on public repos is unlimited, I write my workflows as if they weren't and try to optimise them) and quality (if someone was to look at the current workflow so they can base theirs on it, I would be recommending the current solution of knowing if it *should* need changing, instead of adding a workaround for GitHub hiccups, which if considered would require most workflows to have a lot of added complexity and is a bit of a slippery slope for something that I consider to be a safe assumption).

I think for now I'm going to stick with manually retrying failed jobs and look at how often they occur, and if it's often enough, find a more automated solution. If you want to purely rely on updating Insiders from the Pacman repo, I would also recommend disabling VSCode's automatic updates, which would avoid seeing the in-app notification as described in #2.

**Comment by nihaals** [comment]
This has been implemented with 6ecd85dad6ee9b4405014646aac8046ab9284956.

**Comment by julian-poidevin** [comment]
Great thanks !
